#################################################
# 同步配置，请不要删除任何一个key，如果不慎删除，可删掉文件重新生成。
# 如果遇到问题，可以加群讨论：QQ群：820131534
#################################################
##################################
# 同步功能开关
##################################
同步背包: true
同步末影箱: true
同步血量饱食度: true
同步药水效果: true
同步经验: true
同步成就: true

##################################
# 同步选项
##################################

#当同步锁一直无法解锁时，超过这个时间会强行解锁，建议设置时间足够长，排除掉其他服务器还未保存完数据的情况（单位：秒）
等待时间: 60

#防止服务器崩溃造成数据丢失，每间隔一段时间，将在线玩家的数据保存一次（单位：秒）
自动保存间隔: 60